export { Hero } from "./Hero"
export { Intro } from "./Intro"
export { Benefits } from "./Benefits"
export { How } from "./How"
export { Testimonial1 } from "./Testimonial1"
export { Testimonial2 } from "./Testimonial2"
export { Plans } from "./Plans"
